#!/bin/bash

options=(
	style=round
	width=2.0
	hidpi=on
	"active_color=gradient(top_left=0xffb4befe,bottom_right=0xffcba6f7)"
	inactive_color=0x4445475a
	ax_focus=on
	order=above
)

borders "${options[@]}"
